# Generated by Django 4.2.1 on 2023-06-24 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0003_producto1_itemcarrito'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemCarrito',
            new_name='CarritoItem',
        ),
        migrations.DeleteModel(
            name='Producto1',
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.producto'),
        ),
    ]
