# Generated by Django 4.2.1 on 2023-06-25 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_rename_itemcarrito_carritoitem_delete_producto1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarritoItem',
        ),
    ]
