# Generated by Django 4.2.1 on 2023-06-26 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_envio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envio',
            old_name='nombre',
            new_name='nombre_envio',
        ),
    ]
