# Generated by Django 4.2.1 on 2023-06-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_rename_nombre_envio_nombre_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
